default: &default
  partner_id: '2088511484087918'
  key: 'buhas6b3dxixaipc303rtgiu77s38rky'
  email: 'bjmirrorfan@gmail.com'
  host: abc.com
  port: 3002

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default